@startuml
User << Human >>
(Start the game) as (Use) << Main >>
(Select civilization) as (SelectCiv)
(Quit game) as (Quit)
(Take turn) as (Turn)
(Skip turn) as (Skip)
(Select unit) as (SUnit)
(Deselect unit) as (DSUnit)
(Move) as (Move)
(Attack) as (Attack)
(Produce Unit) as (Produce)
(Produce Melee) as (PM)
(Produce Ranged) as (PR)
(Produce Airborne) as (PA)

(Turn) "<<includes>>"<-- (Turn)

(Use) --->"<<includes>>" (SelectCiv)
(User) ---> (Use)
SelectCiv --->"<<includes>>" (Turn)
(Turn) <---"<<extends>>" (Quit)
(Turn) <---"<<extends>>" (Skip)
(Turn) <---"<<extends>>" (SUnit)
(SUnit) <---"<<extends>>" (DSUnit)
(SUnit) <---"<<extends>>" (Move)
(SUnit) "<<extends>>"<--- (Attack)
(Turn) <---"<<extends>>" (Produce)
(Produce) <---"<<extends>>" (PM)
(Produce) <---"<<extends>>" (PR)
(Produce) <---"<<extends>>" (PA)


' for a Piazza question
' (1) as (Action1)
' (2) as (Action2)
' (3) as (Action3)

' User --> Turn
' (Turn) "<<includes>>"<--- (Turn)
' (Turn) "<<extends>>"<--- (Action1)
' (Turn) "<<extends>>"<--- (Action2)
' (Turn) <---"<<extends>>" (Action3)

@enduml