@startuml

skinparam linetype ortho
hide empty members


package Assets.Scripts.AI {
    class AI {
        AITurnProcessor()
        greedyMove()
    }
}


package Board {
    class Cell {
        -coords : int[]
        -unit : Unit    
        -adjacent : List<Cell>
        +Cell()
        +setCoordinates()
        +addAdjacent()
        +getAdjacent() : List<Cell>
        +getCoordinates() : int[]
        +isFree() : bool
        +setUnit()
        +getUnit() : Unit
    }

    class Assets.Scripts.GameBoard {
        -cells : Cell[][]
        -civs : List<Civilization>
        -unitFactory : UnitFactory
        -civFactory : CivFactory
        -graphicsObserver : GraphicsObserver

        +getCiv() : Civilization
        +spawnUnit()
        +getCells() : Cell[][]
        +getCivilizations() : List<Civilization>
    }
}


AI --> Cell
AI --> Unit
AI <-- Game

Cell --> Unit
Cell --> Cell

GameBoard --> Cell
GameBoard --> Civilization
GameBoard --> UnitFactory
GameBoard --> CivFactory
GameBoard --> GraphicsObserver


@enduml